# Container for MountainSort5
# Reference repo: https://github.com/flatironinstitute/mountainsort5

FROM python:3.11

# Install dependencies and MountainSort5
RUN pip install -U scikit-learn spikeinterface[full] isosplit6>=0.1.0 mountainsort5


